### ISSUE TITLE
Como puxar nome do whatsapp (pushname)

### ISSUE THREAD

**Issue by jailtonsdn** [juniorwmr/botwhatsapp-venom#10]
Olá boa tarde seu projeto ta muito bacana, estou pegando ele e fazendo para integrar ao meu GLPI para abertura de chamado, 
na msg final ele chama o numero e queria chamar no inicio da conversa (Exemplo Olá Jailton) o codigo é:

const phone = from.split('@');

Como chamaria pelo nome???

**Comment by juniorwmr** [comment]
Boa noite. Não compreendi muito bem, consegue explicar um pouco melhor?

**Comment by juniorwmr** [comment]
Fechando a issue por inatividade.
