### ISSUE TITLE
Acredito que eu tenha tido o mesmo problema de um rapaz, o bot não responde. 

### ISSUE THREAD

**Issue by Alex-Lucena-Lacerda** [juniorwmr/botwhatsapp-venom#13]
Copiei o código, e quando vou ler o qr code, o whatsapp abre no chrome, mas não aparece o bot para realizar o teste, fica o whatsapp normal com as minhas conversas,.

**Comment by juniorwmr** [comment]
Opa, fala pessoal, blz?
Então, ao realizar o QRCode Scan, o seu whatsapp (número) será interceptado pelo bot.
Portanto, não é que vai aparecer opções pra você realizar testes...

Se não for isso, por favor, esclarecer o problema.
