### ISSUE TITLE
Conexão após atendimento do funcionário

### ISSUE THREAD

**Issue by RafaRascado** [juniorwmr/botwhatsapp-venom#14]
Junior, primeiramente gostaria de agradecer por compartilhar seu conhecimento. 

Estou tentando criar uma alternativa para que o usuário posso digitar um comando e sair da conversa com a atendente e assim retornar para o menu do chatbot... Poderia me ajudar com isso?

**Comment by juniorwmr** [comment]
Boa tarde. Tudo bem?
Acabei de subir algumas melhorias, inclusive essa que você citou. Dá um conferida lá.
