### ISSUE TITLE
amigo bom dia

### ISSUE THREAD

**Issue by jpmgs1** [juniorwmr/botwhatsapp-venom#3]
sempre que coloco o endereço para finalizar o pedido no whatsapp, lá no GITbash ou no terminal do vscode ele dá erro.

**Comment by juniorwmr** [comment]
Opa, boa tarde. perdão pela demora.

Poderia me informar o erro apresentado?

**Comment by itsfks** [comment]
estou com o mesmo problema :/

(node:6012) UnhandledPromiseRejectionWarning: #<Object>
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✖ [instance: session]: Page Closed

**Comment by jpmgs1** [comment]
consegui um bot semelhante que tem as mesmas funcionalidades, mas o erro é o mesmo que esta citado acima.

**Comment by jpmgs1** [comment]
https://github.com/felipefabricio31/chatbot-whats

ele tem a base semelhante é testei, só falta multiplicar os valores dos itens.
mas 99% funcional

**Comment by juniorwmr** [comment]
Bom dia, pessoal.
Vou verificar o erro apresentado hoje pela noite, assim que tiver um tempinho, e retorno pra vocês.

Grande abraço.

**Comment by jpmgs1** [comment]
consguiu ver alguma coisa? sem aperreio.

**Comment by juniorwmr** [comment]
Boa tarde, pessoal. Desculpa a demora.

Atualizei o pacote e fiz alguns testes. Por favor, verifiquem se o _error_ continua a persistir.

**Comment by mangekyoou** [comment]
Continua o mesmo.

**Comment by cogumm** [comment]
Opa, o erro ainda hoje continua.
Tentei realizar alguns ajustes mas sem sucesso.

`[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {   code: 'ERR_UNHANDLED_REJECTION' `

**Comment by CleytonPinheiro** [comment]
Olá. Conseguiram ver qual o motivo desse erro, estou passando pela mesma situação.

**Comment by juniorwmr** [comment]
Boa noite, pessoal.
Acabei de resolver o problema "ERR_UNHANDLED_REJECTION".

Podem validar?
