### ISSUE TITLE
Erro na hora de passar o endereço.

### ISSUE THREAD

**Issue by FreshPhp** [juniorwmr/botwhatsapp-venom#9]
Assim que eu coloco o endereço para o pedido, aparece o seguinte erro:

Error when sending message {
  me: {},
  erro: true,
  text: 'It is necessary to write a text!',
  status: null,
  result: null
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by juniorwmr** [comment]
Boa noite, ainda está com esse problema?

**Comment by juniorwmr** [comment]
@FreshPhp, boa noite. Acabei de subir algumas melhorias, pode tentar de novo e me retornar?
